openapi: 3.1.0
info:
  version: 1.0.0
  title: Pharmacy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of pharmacy app
tags:
  - name: User
    description: Auth operations.
  - name: Products
    description: Operations about products.
  - name: Reviews
    description: Operations about reviews.
  - name: Stores
    description: Operations about stores.
  - name: Cart
    description: Operations about cart.
servers:
  - url: http://localhost:3000
  - url: https://pharmacy-backend-kwps.onrender.com
paths:
  /user/register:
    post:
      $ref: ../swagger/paths/user/register.yaml
  /user/login:
    post:
      $ref: ../swagger/paths/user/login.yaml
  /user/refresh:
    post:
      $ref: ../swagger/paths/user/refresh.yaml
  /user/logout:
    post:
      $ref: '../swagger/paths/user/logout.yaml'
  /user/user-info:
    get:
      $ref: '../swagger/paths/user/getUser.yaml'
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
  /products/{id}:
    get:
      $ref: ../swagger/paths/products/{id}/get.yaml
  /customer-reviews:
    get:
      $ref: ../swagger/paths/reviews/get.yaml
  /stores:
    get:
      $ref: ../swagger/paths/stores/get.yaml
  /stores/nearest:
    get:
      $ref: ../swagger/paths/stores/getNearest.yaml
  /cart:
    get:
      $ref: ../swagger/paths/cart/get.yaml
    post:
      $ref: ../swagger/paths/cart/post.yaml
  /cart/update/{cartId}/{productId}:
    put:
      $ref: ../swagger/paths/cart/put.yaml
  /cart/{cartId}/{id}:
    delete:
      $ref: ../swagger/paths/cart/{cartId}/{id}/delete.yaml
  /cart/checkout:
    post:
      $ref: ../swagger/paths/cart/placeOrder.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
