openapi: 3.1.0
info:
  version: 1.0.0
  title: Pharmacy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of pharmacy app
tags:
  - name: User
    description: Auth operations.
  - name: Products
    description: Operations about products.
  - name: Reviews
    description: Operations about reviews.
  - name: Stores
    description: Operations about stores.
  - name: Cart
    description: Operations about cart.
servers:
  - url: http://localhost:3000
  - url: https://pharmacy-backend-theta.vercel.app
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
  /products/{id}:
    get:
      $ref: ../swagger/paths/products/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
