type: object
required:
  - _id
  - photo
  - name
  - suppliers
  - stock
  - price
  - category
properties:
  _id:
    description: "Product's id"
    type: string
    example: 65e4decdd286b30065d54af9
  id:
    description: "Product's id"
    type: string
    example: 2
  photo:
    description: "Link to product's photo"
    type: string
    example: https://res.cloudinary.com/uqwgdu/image/upload/image.png
  name:
    description: "Product's name"
    type: string
    example: Aspirin
  suppliers:
    description: "Product's supplier"
    type: string
    example: Square
  stock:
    description: 'Quantity of products in stock'
    type: string
    example: 12
  price:
    description: "Product's price"
    type: string
    example: 86.99
  category:
    description: "Product's category"
    type: string
    example: Hand
